apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  type: NodePort
  selector:
    app: rails
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - name: rails
          image: hello-kubernetes/rails:3611881
          ports:
            - containerPort: 3000
